name: CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # =========================
      # CLONAR REPOSITORIO
      # =========================
      - name: Checkout repository
        uses: actions/checkout@v4

      # =========================
      # CONFIGURAR NODE.JS
      # =========================
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      # =========================
      # BACKEND
      # =========================
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      # =========================
      # FRONTEND
      # =========================
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      # =========================
      # ESLINT
      # =========================
      - name: Run frontend lint
        working-directory: ./frontend
        run: npm run lint

      # =========================
      # BUILD FRONTEND
      # =========================
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # =========================
      # VALIDAR DOCKER COMPOSE
      # =========================
      - name: Validate Docker Compose
        run: docker compose config

      # =========================
      # PIPELINE EXITOSO
      # =========================
      - name: Pipeline Success
        run: echo "CI/CD Pipeline ejecutado correctamente"